<?php
	$preview_array = array("abs"=>array(
			array("1"=>array(
				array("05:00","Umagang Kay Ganda Anthony Taberna Amy Perez Jorge Carino Ariel Ureta Winnie Cordero Grecthen Ho and Atom Araullo"),
				array("08:00","Sailor Moon"),
				array("08:30","Naruto Shippuden (Season 4)"),
				array("09:00","Kris TV Kris Aquino"),
				array("10:00","Kapamilya Blockbusters"),
				array("11:30"," It's Showtime Vhong Navarro Anne Curtis Vice Ganda Kuya Kim Atienza Jugs Jugetta Teddy Corpuz Jhong Hilario Karylle Coleen Garcia Billy Crawford and Ryan Bang "),
				array("14:45","Salvador Royales's Mundo Man ay Magunaw Nikki Gil Ejay Falcon and Empress Schuck"),
				array("15:30","Kung Ako'y Iiwan Mo Bangs Garcia Jake Cuenca and Shaina Magdayao"),
				array("16:30","Pinoy Big Brother Unliday Toni Gonzaga"),
				array("17:00","Precious Hearts Romances: Lumayo Ka Man sa Akin"),
				array("17:45","Wako Wako"),
				array("18:30","TV Patrol Noli De Castro Ted Failon and Bernadette Sembrano-Aguinaldo with Kuya Kim Atienza Grecthen Fullido Marc Logan and Winnie Cordero"),
				array("19:45","E-Boy"),
				array("20:30","Dahil sa Pag-ibig Christoper de Leon Piolo Pascual Cristine Reyes Jericho Rosales and Maricar Reyes"),
				array("21:15","Walang Hanggan (2012 TV Series) Coco Martin Julia Montes and Paulo Avelino"),
				array("22:00","Pinoy Big Brother Unlinight Robi Domingo"),
				array("22:30","City Hunter"),
				array("23:00","Bandila Karen Davilla Julius Babao and Boy Abunda"),
				array("23:45","ABS-CBN News and Current Affairs programs")
				)
			),	
			array("2"=>array(
				array("05:00","Umagang Kay Ganda Anthony Taberna Amy Perez Jorge Carino Ariel Ureta Winnie Cordero Grecthen Ho and Atom Araullo"),
				array("08:00","Sailor Moon"),
				array("08:30","Naruto Shippuden (Season 4)"),
				array("09:00","Kris TV Kris Aquino"),
				array("10:00","Kapamilya Blockbusters"),
				array("11:30"," It's Showtime Vhong Navarro Anne Curtis Vice Ganda Kuya Kim Atienza Jugs Jugetta Teddy Corpuz Jhong Hilario Karylle Coleen Garcia Billy Crawford and Ryan Bang "),
				array("14:45","Salvador Royales's Mundo Man ay Magunaw Nikki Gil Ejay Falcon and Empress Schuck"),
				array("15:30","Kung Ako'y Iiwan Mo Bangs Garcia Jake Cuenca and Shaina Magdayao"),
				array("16:30","Pinoy Big Brother Unliday Toni Gonzaga"),
				array("17:00","Precious Hearts Romances: Lumayo Ka Man sa Akin"),
				array("17:45","Wako Wako"),
				array("18:30","TV Patrol Noli De Castro Ted Failon and Bernadette Sembrano-Aguinaldo with Kuya Kim Atienza Grecthen Fullido Marc Logan and Winnie Cordero"),
				array("19:45","E-Boy"),
				array("20:30","Dahil sa Pag-ibig Christoper de Leon Piolo Pascual Cristine Reyes Jericho Rosales and Maricar Reyes"),
				array("21:15","Walang Hanggan (2012 TV Series) Coco Martin Julia Montes and Paulo Avelino"),
				array("22:00","Pinoy Big Brother Unlinight Robi Domingo"),
				array("22:30","City Hunter"),
				array("23:00","Bandila Karen Davilla Julius Babao and Boy Abunda"),
				array("23:45","ABS-CBN News and Current Affairs programs")
				)
			),	
			array("3"=>array(
				array("05:00","Umagang Kay Ganda Anthony Taberna Amy Perez Jorge Carino Ariel Ureta Winnie Cordero Grecthen Ho and Atom Araullo"),
				array("08:00","Sailor Moon"),
				array("08:30","Naruto Shippuden (Season 4)"),
				array("09:00","Kris TV Kris Aquino"),
				array("10:00","Kapamilya Blockbusters"),
				array("11:30"," It's Showtime Vhong Navarro Anne Curtis Vice Ganda Kuya Kim Atienza Jugs Jugetta Teddy Corpuz Jhong Hilario Karylle Coleen Garcia Billy Crawford and Ryan Bang "),
				array("14:45","Salvador Royales's Mundo Man ay Magunaw Nikki Gil Ejay Falcon and Empress Schuck"),
				array("15:30","Kung Ako'y Iiwan Mo Bangs Garcia Jake Cuenca and Shaina Magdayao"),
				array("16:30","Pinoy Big Brother Unliday Toni Gonzaga"),
				array("17:00","Precious Hearts Romances: Lumayo Ka Man sa Akin"),
				array("17:45","Wako Wako"),
				array("18:30","TV Patrol Noli De Castro Ted Failon and Bernadette Sembrano-Aguinaldo with Kuya Kim Atienza Grecthen Fullido Marc Logan and Winnie Cordero"),
				array("19:45","E-Boy"),
				array("20:30","Dahil sa Pag-ibig Christoper de Leon Piolo Pascual Cristine Reyes Jericho Rosales and Maricar Reyes"),
				array("21:15","Walang Hanggan (2012 TV Series) Coco Martin Julia Montes and Paulo Avelino"),
				array("22:00","Pinoy Big Brother Unlinight Robi Domingo"),
				array("22:30","City Hunter"),
				array("23:00","Bandila Karen Davilla Julius Babao and Boy Abunda"),
				array("23:45","ABS-CBN News and Current Affairs programs")
				)
			),	
			array("4"=>array(
				array("05:00","Umagang Kay Ganda Anthony Taberna Amy Perez Jorge Carino Ariel Ureta Winnie Cordero Grecthen Ho and Atom Araullo"),
				array("08:00","Sailor Moon"),
				array("08:30","Naruto Shippuden (Season 4)"),
				array("09:00","Kris TV Kris Aquino"),
				array("10:00","Kapamilya Blockbusters"),
				array("11:30"," It's Showtime Vhong Navarro Anne Curtis Vice Ganda Kuya Kim Atienza Jugs Jugetta Teddy Corpuz Jhong Hilario Karylle Coleen Garcia Billy Crawford and Ryan Bang "),
				array("14:45","Salvador Royales's Mundo Man ay Magunaw Nikki Gil Ejay Falcon and Empress Schuck"),
				array("15:30","Kung Ako'y Iiwan Mo Bangs Garcia Jake Cuenca and Shaina Magdayao"),
				array("16:30","Pinoy Big Brother Unliday Toni Gonzaga"),
				array("17:00","Precious Hearts Romances: Lumayo Ka Man sa Akin"),
				array("17:45","Wako Wako"),
				array("18:30","TV Patrol Noli De Castro Ted Failon and Bernadette Sembrano-Aguinaldo with Kuya Kim Atienza Grecthen Fullido Marc Logan and Winnie Cordero"),
				array("19:45","E-Boy"),
				array("20:30","Dahil sa Pag-ibig Christoper de Leon Piolo Pascual Cristine Reyes Jericho Rosales and Maricar Reyes"),
				array("21:15","Walang Hanggan (2012 TV Series) Coco Martin Julia Montes and Paulo Avelino"),
				array("22:00","Pinoy Big Brother Unlinight Robi Domingo"),
				array("22:30","City Hunter"),
				array("23:00","Bandila Karen Davilla Julius Babao and Boy Abunda"),
				array("23:45","ABS-CBN News and Current Affairs programs")
				)
			),	
			array("5"=>array(
				array("05:00","Umagang Kay Ganda Anthony Taberna Amy Perez Jorge Carino Ariel Ureta Winnie Cordero Grecthen Ho and Atom Araullo"),
				array("08:00","Sailor Moon"),
				array("08:30","Naruto Shippuden (Season 4)"),
				array("09:00","Kris TV Kris Aquino"),
				array("10:00","Kapamilya Blockbusters"),
				array("11:30"," It's Showtime Vhong Navarro Anne Curtis Vice Ganda Kuya Kim Atienza Jugs Jugetta Teddy Corpuz Jhong Hilario Karylle Coleen Garcia Billy Crawford and Ryan Bang "),
				array("14:45","Salvador Royales's Mundo Man ay Magunaw Nikki Gil Ejay Falcon and Empress Schuck"),
				array("15:30","Kung Ako'y Iiwan Mo Bangs Garcia Jake Cuenca and Shaina Magdayao"),
				array("16:30","Pinoy Big Brother Unliday Toni Gonzaga"),
				array("17:00","Precious Hearts Romances: Lumayo Ka Man sa Akin"),
				array("17:45","Wako Wako"),
				array("18:30","TV Patrol Noli De Castro Ted Failon and Bernadette Sembrano-Aguinaldo with Kuya Kim Atienza Grecthen Fullido Marc Logan and Winnie Cordero"),
				array("19:45","E-Boy"),
				array("20:30","Dahil sa Pag-ibig Christoper de Leon Piolo Pascual Cristine Reyes Jericho Rosales and Maricar Reyes"),
				array("21:15","Walang Hanggan (2012 TV Series) Coco Martin Julia Montes and Paulo Avelino"),
				array("22:00","Pinoy Big Brother Unlinight Robi Domingo"),
				array("22:30","City Hunter"),
				array("23:00","Bandila Karen Davilla Julius Babao and Boy Abunda"),
				array("23:45","ABS-CBN News and Current Affairs programs")
				)
			),	
			array("6"=>array(
				array("05:30","DZMM Teleradyo"),
				array("06:00","Salamat Dok Alvin Elchino and Bernadette Sembrano-Aguinaldo "),
				array("07:00","Kabuhayang Swak na Swak Bobby Yan Carlos Agassi and Dimples Romanna"),
				array("07:30","Honey, Watch Out!"),
				array("08:15","Go Diego Go!"),
				array("08:45","The Penguins of Madagascar"),
				array("09:15","The Adventures of Jimmy Neutron"),
				array("09:45","Kapamilya Kiddie Blockbusters"),
				array("11:30","It's Showtime Vhong Navarro Anne Curtis Vice Ganda Kuya Kim Atienza Jugs Jugetta Teddy Corpuz Jhong Hilario Karylle Coleen Garcia and Ryan Bang "),
				array("14:30","Showbiz Inside Report Carmina Villaroel Janice de Belen Joey Marquez and Ogie Diaz"),
				array("15:30","Oka2Kat (2012 TV Series)"),
				array("16:30","Failon Ngayon Ted Failon"),
				array("17:00","MGB: Magandang Gabi, Bayan Noli de Castro"),
				array("18:00","Kapamilya, Deal or No Deal Luis Manzano"),
				array("19:00","Wansapanataym (all new)"),
				array("19:45","Maalaala Mo Kaya Ms.Charo Santos"),
				array("20:30","TV Patrol Weekend Alvin Elchino and Zen Hernandez"),
				array("21:00","Toda Max Robin Padilla Angel Locsin Ai Ai delas Alas and Vhong Navarro"),
				array("21:45","Pinoy Big Brother Unlimited Bianca Gonzales Toni Gonzaga and Robi Domingo"),
				array("22:45","Banana Split (now Banana Sundae) Angelica Panganiban Pokwang Jayson Gainza John Pratts Pooh Jessy Mendiola JC de Vera Alex Gonzaga and Zanjoe Marudo"),
				array("23:45","Toda Max Robin Padilla Angel Locsin Ai Ai delas Alas and Vhong Navarro")
				)
			),	
			array("0"=>array(
				array("00:30","Sports Unlimited Dyan Castilejo-Garcia and Marc Nelson"),
				array("06:00","Sunday TV Mass: The Healing Eucharist"),
				array("07:00","Kabuhayang Swak na Swak Bobby Yan Carlos Agassi and Dimples Romanna"),
				array("07:30","Salamat Dok Alvin Elchino and Bernadette Sembrano-Aguinaldo"),
				array("08:30","Spider-Man"),
				array("09:00"," The Incredible Hulk"),
				array("09:30"," Matanglawin Kuya Kim Atienza"),
				array("10:30","Kapamilya Mega Blockbusters"),
				array("12:15"," ASAP (variety show)"),
				array("15:00","Luv U Kiray Celis Angeli Gonzales Francis Magadayao Igi Boy Flores CJ Navato Michelle Vito Marco Gumabao and Jarius Aquino"),
				array("16:00","The Buzz (talk show) Mr.Boy Abunda Ms.Kris Aquino Ms.Phoemela Baranda and Ms.Toni Gonzaga"),
				array("18:00","Rated K Ms.Korina Sanchez-Roxas"),
				array("19:00","Goin' Bulilit Goin Bulilit Kids with Dagul"),
				array("20:00","TV Patrol Weekend Alvin Elchino and Zen Hernandez"),
				array("20:45","Sarah G. Live! Sarah Geronimo"),
				array("21:30","Pinoy Big Brother Unlimited Toni Gonzaga"),
				array("22:30","Gandang Gabi, Vice! Vice Ganda"),
				array("21:30","Sunday's Best (special presentations) ")
				)
			)
		),	
			
		/////////////////////////////////////////////////
			
		"inc"=>array(
			array("1"=>array(
				array("0:00","INC TV News"),
				array("1:50","Church News"),
				array("02:30","Last Wo"),
				array("04:00","Church News"),
				array("06:00","Talk Show"),
				array("08:00","INC TV Teleradyo"),
				array("10:00","Church News"),
				array("12:00","Church News"),
				)
			),	
			array("2"=>array(
				array("0:00","INC TV News"),
				array("1:50","Church News"),
				array("02:30","Last Wo"),
				array("04:00","Church News"),
				array("06:00","Talk Show"),
				array("08:00","INC TV Teleradyo"),
				array("10:00","Church News"),
				array("12:00","Church News"),
				)
			),	
			array("3"=>array(
				array("0:00","INC TV News"),
				array("1:50","Church News"),
				array("02:30","Last Wo"),
				array("04:00","Church News"),
				array("06:00","Talk Show"),
				array("08:00","INC TV Teleradyo"),
				array("10:00","Church News"),
				array("12:00","Church News"),
				)
			),	
			array("4"=>array(
				array("0:00","INC TV News"),
				array("1:50","Church News"),
				array("02:30","Last Wo"),
				array("04:00","Church News"),
				array("06:00","Talk Show"),
				array("08:00","INC TV Teleradyo"),
				array("10:00","Church News"),
				array("12:00","Church News"),
				)
			),	
			array("5"=>array(
				array("0:00","INC TV News"),
				array("1:50","Church News"),
				array("02:30","Last Wo"),
				array("04:00","Church News"),
				array("06:00","Talk Show"),
				array("08:00","INC TV Teleradyo"),
				array("10:00","Church News"),
				array("12:00","Church News"),
				)
			),	
			array("6"=>array(
				array("00:30","INC TV Teleradyo"),
				array("04:00","INC TV Cebu Teleradyo "),
				array("05:00","Off-air (shared tomorrow INC TV no schedule programs 12nn - 4pm)"),
				)
			),	
			array("0"=>array(
				array("00:00","Church News"),
				array("04:00"," INC TV Teleradyo"),
				array("07:00","INC TV Box Office"),
				array("12:00","Off-air (shared tomorrow INC TV no schedule programs 12nn - 5pm)"),
				)
			)
		),
				
		////////////////////////////////////////////////////
				
		"abc"=>array(
			array("1"=>array(
				array("05:00","Umagang Kay Ganda Anthony Taberna Amy Perez Jorge Carino Ariel Ureta Winnie Cordero Grecthen Ho and Atom Araullo"),
				array("08:00","Sailor Moon"),
				array("08:30","Naruto Shippuden (Season 4)"),
				array("09:00","Kris TV Kris Aquino"),
				array("10:00","Kapamilya Blockbusters"),
				array("11:30"," It's Showtime Vhong Navarro Anne Curtis Vice Ganda Kuya Kim Atienza Jugs Jugetta Teddy Corpuz Jhong Hilario Karylle Coleen Garcia Billy Crawford and Ryan Bang "),
				array("14:45","Salvador Royales's Mundo Man ay Magunaw Nikki Gil Ejay Falcon and Empress Schuck"),
				array("15:30","Kung Ako'y Iiwan Mo Bangs Garcia Jake Cuenca and Shaina Magdayao"),
				array("16:30","Pinoy Big Brother Unliday Toni Gonzaga"),
				array("17:00","Precious Hearts Romances: Lumayo Ka Man sa Akin"),
				array("17:45","Wako Wako"),
				array("18:30","TV Patrol Noli De Castro Ted Failon and Bernadette Sembrano-Aguinaldo with Kuya Kim Atienza Grecthen Fullido Marc Logan and Winnie Cordero"),
				array("19:45","E-Boy"),
				array("20:30","Dahil sa Pag-ibig Christoper de Leon Piolo Pascual Cristine Reyes Jericho Rosales and Maricar Reyes"),
				array("21:15","Walang Hanggan (2012 TV Series) Coco Martin Julia Montes and Paulo Avelino"),
				array("22:00","Pinoy Big Brother Unlinight Robi Domingo"),
				array("22:30","City Hunter"),
				array("23:00","Bandila Karen Davilla Julius Babao and Boy Abunda"),
				array("23:45","ABS-CBN News and Current Affairs programs")
				)
			),	
			array("2"=>array(
				array("05:00","Umagang Kay Ganda Anthony Taberna Amy Perez Jorge Carino Ariel Ureta Winnie Cordero Grecthen Ho and Atom Araullo"),
				array("08:00","Sailor Moon"),
				array("08:30","Naruto Shippuden (Season 4)"),
				array("09:00","Kris TV Kris Aquino"),
				array("10:00","Kapamilya Blockbusters"),
				array("11:30"," It's Showtime Vhong Navarro Anne Curtis Vice Ganda Kuya Kim Atienza Jugs Jugetta Teddy Corpuz Jhong Hilario Karylle Coleen Garcia Billy Crawford and Ryan Bang "),
				array("14:45","Salvador Royales's Mundo Man ay Magunaw Nikki Gil Ejay Falcon and Empress Schuck"),
				array("15:30","Kung Ako'y Iiwan Mo Bangs Garcia Jake Cuenca and Shaina Magdayao"),
				array("16:30","Pinoy Big Brother Unliday Toni Gonzaga"),
				array("17:00","Precious Hearts Romances: Lumayo Ka Man sa Akin"),
				array("17:45","Wako Wako"),
				array("18:30","TV Patrol Noli De Castro Ted Failon and Bernadette Sembrano-Aguinaldo with Kuya Kim Atienza Grecthen Fullido Marc Logan and Winnie Cordero"),
				array("19:45","E-Boy"),
				array("20:30","Dahil sa Pag-ibig Christoper de Leon Piolo Pascual Cristine Reyes Jericho Rosales and Maricar Reyes"),
				array("21:15","Walang Hanggan (2012 TV Series) Coco Martin Julia Montes and Paulo Avelino"),
				array("22:00","Pinoy Big Brother Unlinight Robi Domingo"),
				array("22:30","City Hunter"),
				array("23:00","Bandila Karen Davilla Julius Babao and Boy Abunda"),
				array("23:45","ABS-CBN News and Current Affairs programs")
				)
			),	
			array("3"=>array(
				array("05:00","Umagang Kay Ganda Anthony Taberna Amy Perez Jorge Carino Ariel Ureta Winnie Cordero Grecthen Ho and Atom Araullo"),
				array("08:00","Sailor Moon"),
				array("08:30","Naruto Shippuden (Season 4)"),
				array("09:00","Kris TV Kris Aquino"),
				array("10:00","Kapamilya Blockbusters"),
				array("11:30"," It's Showtime Vhong Navarro Anne Curtis Vice Ganda Kuya Kim Atienza Jugs Jugetta Teddy Corpuz Jhong Hilario Karylle Coleen Garcia Billy Crawford and Ryan Bang "),
				array("14:45","Salvador Royales's Mundo Man ay Magunaw Nikki Gil Ejay Falcon and Empress Schuck"),
				array("15:30","Kung Ako'y Iiwan Mo Bangs Garcia Jake Cuenca and Shaina Magdayao"),
				array("16:30","Pinoy Big Brother Unliday Toni Gonzaga"),
				array("17:00","Precious Hearts Romances: Lumayo Ka Man sa Akin"),
				array("17:45","Wako Wako"),
				array("18:30","TV Patrol Noli De Castro Ted Failon and Bernadette Sembrano-Aguinaldo with Kuya Kim Atienza Grecthen Fullido Marc Logan and Winnie Cordero"),
				array("19:45","E-Boy"),
				array("20:30","Dahil sa Pag-ibig Christoper de Leon Piolo Pascual Cristine Reyes Jericho Rosales and Maricar Reyes"),
				array("21:15","Walang Hanggan (2012 TV Series) Coco Martin Julia Montes and Paulo Avelino"),
				array("22:00","Pinoy Big Brother Unlinight Robi Domingo"),
				array("22:30","City Hunter"),
				array("23:00","Bandila Karen Davilla Julius Babao and Boy Abunda"),
				array("23:45","ABS-CBN News and Current Affairs programs")
				)
			),	
			array("4"=>array(
				array("05:00","Umagang Kay Ganda Anthony Taberna Amy Perez Jorge Carino Ariel Ureta Winnie Cordero Grecthen Ho and Atom Araullo"),
				array("08:00","Sailor Moon"),
				array("08:30","Naruto Shippuden (Season 4)"),
				array("09:00","Kris TV Kris Aquino"),
				array("10:00","Kapamilya Blockbusters"),
				array("11:30"," It's Showtime Vhong Navarro Anne Curtis Vice Ganda Kuya Kim Atienza Jugs Jugetta Teddy Corpuz Jhong Hilario Karylle Coleen Garcia Billy Crawford and Ryan Bang "),
				array("14:45","Salvador Royales's Mundo Man ay Magunaw Nikki Gil Ejay Falcon and Empress Schuck"),
				array("15:30","Kung Ako'y Iiwan Mo Bangs Garcia Jake Cuenca and Shaina Magdayao"),
				array("16:30","Pinoy Big Brother Unliday Toni Gonzaga"),
				array("17:00","Precious Hearts Romances: Lumayo Ka Man sa Akin"),
				array("17:45","Wako Wako"),
				array("18:30","TV Patrol Noli De Castro Ted Failon and Bernadette Sembrano-Aguinaldo with Kuya Kim Atienza Grecthen Fullido Marc Logan and Winnie Cordero"),
				array("19:45","E-Boy"),
				array("20:30","Dahil sa Pag-ibig Christoper de Leon Piolo Pascual Cristine Reyes Jericho Rosales and Maricar Reyes"),
				array("21:15","Walang Hanggan (2012 TV Series) Coco Martin Julia Montes and Paulo Avelino"),
				array("22:00","Pinoy Big Brother Unlinight Robi Domingo"),
				array("22:30","City Hunter"),
				array("23:00","Bandila Karen Davilla Julius Babao and Boy Abunda"),
				array("23:45","ABS-CBN News and Current Affairs programs")
				)
			),	
			array("5"=>array(
				array("05:00","Umagang Kay Ganda Anthony Taberna Amy Perez Jorge Carino Ariel Ureta Winnie Cordero Grecthen Ho and Atom Araullo"),
				array("08:00","Sailor Moon"),
				array("08:30","Naruto Shippuden (Season 4)"),
				array("09:00","Kris TV Kris Aquino"),
				array("10:00","Kapamilya Blockbusters"),
				array("11:30"," It's Showtime Vhong Navarro Anne Curtis Vice Ganda Kuya Kim Atienza Jugs Jugetta Teddy Corpuz Jhong Hilario Karylle Coleen Garcia Billy Crawford and Ryan Bang "),
				array("14:45","Salvador Royales's Mundo Man ay Magunaw Nikki Gil Ejay Falcon and Empress Schuck"),
				array("15:30","Kung Ako'y Iiwan Mo Bangs Garcia Jake Cuenca and Shaina Magdayao"),
				array("16:30","Pinoy Big Brother Unliday Toni Gonzaga"),
				array("17:00","Precious Hearts Romances: Lumayo Ka Man sa Akin"),
				array("17:45","Wako Wako"),
				array("18:30","TV Patrol Noli De Castro Ted Failon and Bernadette Sembrano-Aguinaldo with Kuya Kim Atienza Grecthen Fullido Marc Logan and Winnie Cordero"),
				array("19:45","E-Boy"),
				array("20:30","Dahil sa Pag-ibig Christoper de Leon Piolo Pascual Cristine Reyes Jericho Rosales and Maricar Reyes"),
				array("21:15","Walang Hanggan (2012 TV Series) Coco Martin Julia Montes and Paulo Avelino"),
				array("22:00","Pinoy Big Brother Unlinight Robi Domingo"),
				array("22:30","City Hunter"),
				array("23:00","Bandila Karen Davilla Julius Babao and Boy Abunda"),
				array("23:45","ABS-CBN News and Current Affairs programs")
				)
			),	
			array("6"=>array(
				array("05:30","DZMM Teleradyo"),
				array("06:00","Salamat Dok Alvin Elchino and Bernadette Sembrano-Aguinaldo "),
				array("07:00","Kabuhayang Swak na Swak Bobby Yan Carlos Agassi and Dimples Romanna"),
				array("07:30","Honey, Watch Out!"),
				array("08:15","Go Diego Go!"),
				array("08:45","The Penguins of Madagascar"),
				array("09:15","The Adventures of Jimmy Neutron"),
				array("09:45","Kapamilya Kiddie Blockbusters"),
				array("11:30","It's Showtime Vhong Navarro Anne Curtis Vice Ganda Kuya Kim Atienza Jugs Jugetta Teddy Corpuz Jhong Hilario Karylle Coleen Garcia and Ryan Bang "),
				array("14:30","Showbiz Inside Report Carmina Villaroel Janice de Belen Joey Marquez and Ogie Diaz"),
				array("15:30","Oka2Kat (2012 TV Series)"),
				array("16:30","Failon Ngayon Ted Failon"),
				array("17:00","MGB: Magandang Gabi, Bayan Noli de Castro"),
				array("18:00","Kapamilya, Deal or No Deal Luis Manzano"),
				array("19:00","Wansapanataym (all new)"),
				array("19:45","Maalaala Mo Kaya Ms.Charo Santos"),
				array("20:30","TV Patrol Weekend Alvin Elchino and Zen Hernandez"),
				array("21:00","Toda Max Robin Padilla Angel Locsin Ai Ai delas Alas and Vhong Navarro"),
				array("21:45","Pinoy Big Brother Unlimited Bianca Gonzales Toni Gonzaga and Robi Domingo"),
				array("22:45","Banana Split (now Banana Sundae) Angelica Panganiban Pokwang Jayson Gainza John Pratts Pooh Jessy Mendiola JC de Vera Alex Gonzaga and Zanjoe Marudo"),
				array("23:45","Toda Max Robin Padilla Angel Locsin Ai Ai delas Alas and Vhong Navarro")
				)
			),	
			array("0"=>array(
				array("00:30","Sports Unlimited Dyan Castilejo-Garcia and Marc Nelson"),
				array("06:00","Sunday TV Mass: The Healing Eucharist"),
				array("07:00","Kabuhayang Swak na Swak Bobby Yan Carlos Agassi and Dimples Romanna"),
				array("07:30","Salamat Dok Alvin Elchino and Bernadette Sembrano-Aguinaldo"),
				array("08:30","Spider-Man"),
				array("09:00"," The Incredible Hulk"),
				array("09:30"," Matanglawin Kuya Kim Atienza"),
				array("10:30","Kapamilya Mega Blockbusters"),
				array("12:15"," ASAP (variety show)"),
				array("15:00","Luv U Kiray Celis Angeli Gonzales Francis Magadayao Igi Boy Flores CJ Navato Michelle Vito Marco Gumabao and Jarius Aquino"),
				array("16:00","The Buzz (talk show) Mr.Boy Abunda Ms.Kris Aquino Ms.Phoemela Baranda and Ms.Toni Gonzaga"),
				array("18:00","Rated K Ms.Korina Sanchez-Roxas"),
				array("19:00","Goin' Bulilit Goin Bulilit Kids with Dagul"),
				array("20:00","TV Patrol Weekend Alvin Elchino and Zen Hernandez"),
				array("20:45","Sarah G. Live! Sarah Geronimo"),
				array("21:30","Pinoy Big Brother Unlimited Toni Gonzaga"),
				array("22:30","Gandang Gabi, Vice! Vice Ganda"),
				array("21:30","Sunday's Best (special presentations) ")
				)
			)
		),
	);



?>